"use client";
import {useEffect,useState} from "react";
import {places,type Group} from "@/lib/travel/model";
type Geometry={type:string;coordinates:number[][][]|number[][][][]};
// Equirectangular projection with longitude scaled at 47°N.
function xy(lon:number,lat:number){return [(lon+5.5)*42,(51.3-lat)*62];}
export default function FranceMap({groups,destinations,selected,onSelect,ranked}:{groups:Group[];destinations:string[];selected?:string;onSelect:(id:string)=>void;ranked:string[]}){
 const [geometries,setGeometries]=useState<Geometry[]>([]);
 useEffect(()=>{fetch("/france-regions.geojson").then(r=>r.json() as Promise<{features:{geometry:Geometry}[]}>).then(r=>setGeometries(r.features.map((f:{geometry:Geometry})=>f.geometry))).catch(()=>{});},[]);
 const origins=[...new Set(groups.map(g=>g.place))].map(id=>places.find(p=>p.id===id)!).filter(Boolean);
 const target=places.find(p=>p.id===selected);
 return <svg className="france-map" viewBox="0 0 590 575" aria-label="Carte des départs et destinations en France" role="group"><defs><pattern id="grid" width="42" height="62" patternUnits="userSpaceOnUse"><path d="M 42 0 L 0 0 0 62" fill="none" stroke="#dae5f1" strokeWidth=".5"/></pattern></defs><rect width="590" height="575" fill="#f0f5fa"/><rect width="590" height="575" fill="url(#grid)"/>{geometries.map((g,i)=>{const polygons=g.type==="Polygon"?[g.coordinates as number[][][]]:g.coordinates as number[][][][];return <path key={i} d={polygons.map(p=>p.map(r=>r.map(([lon,lat],j)=>`${j?"L":"M"}${xy(lon,lat).join(",")}`).join(" ")+"Z").join(" ")).join(" ")} fill="#fff" fillRule="evenodd" stroke="#d5dfec" strokeWidth=".8"/>;})}<text x="57" y="280" className="sea-label" transform="rotate(-70 57 280)">OCÉAN ATLANTIQUE</text><text x="210" y="555" className="sea-label">MER MÉDITERRANÉE</text>{target&&origins.map(p=><line key={p.id} x1={xy(p.lon,p.lat)[0]} y1={xy(p.lon,p.lat)[1]} x2={xy(target.lon,target.lat)[0]} y2={xy(target.lon,target.lat)[1]} stroke="#6287e9" opacity=".4" strokeDasharray="4 5"/>)}{destinations.map(id=>{const p=places.find(p=>p.id===id);if(!p)return null;const [x,y]=xy(p.lon,p.lat);const active=id===selected;return <g key={id} role="button" tabIndex={0} aria-label={`Comparer ${p.name}${ranked.includes(id)?", données complètes":""}`} aria-pressed={active} onClick={()=>onSelect(id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(id);}}} className="map-point"><title>{p.name}</title><circle cx={x} cy={y} r={13} fill="transparent"/>{active&&<circle cx={x} cy={y} r="14" fill="#2458e6" opacity=".14"/>}<circle cx={x} cy={y} r={active?6:4} fill={active?"#2458e6":ranked.includes(id)?"#5574b9":"#a1b3cb"} stroke="white" strokeWidth="1.5"/></g>})}{origins.map(p=>{const [x,y]=xy(p.lon,p.lat);const same=p.id===selected;return <g key={p.id} pointerEvents="none"><circle cx={x} cy={y} r={same?5:5.5} fill={same?"#2458e6":"#142d55"} stroke="white" strokeWidth="2"/><text x={x+(p.id==="mulhouse"?-10:10)} y={y+(p.id==="clermont"?20:-10)} textAnchor={p.id==="mulhouse"?"end":"start"} className="origin-label">{p.name}{p.id==="lyon"&&groups.filter(g=>g.place==="lyon").length>1?" ×2":""}</text></g>})}{target&&!origins.some(p=>p.id===target.id)&&<g pointerEvents="none"><rect x={xy(target.lon,target.lat)[0]-60} y={xy(target.lon,target.lat)[1]-37} width="120" height="25" rx="6" fill="#2458e6"/><text x={xy(target.lon,target.lat)[0]} y={xy(target.lon,target.lat)[1]-20} textAnchor="middle" fill="white" fontSize="14" fontWeight="600">{target.name}</text></g>}</svg>
}
