import {useState,useEffect,useMemo,useRef} from "react";
import {MapPin,TrainFront,Car,ArrowRight,Users,ChevronDown,Info,Plus,LoaderCircle,ExternalLink,Settings2,CalendarDays} from "lucide-react";
import {computeTrip} from "@/lib/travel/client";
import {loadRailIndex,type RailIndex} from "@/lib/travel/rail-client";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Table,TableHeader,TableBody,TableHead,TableCell,TableRow} from "@/components/ui/table";
import {Checkbox} from "@/components/ui/checkbox";
import {Progress} from "@/components/ui/progress";
import {initialGroups,places,defaultDestinations,scenarios,rank,duration,originFor,tripKey,validMinutes,type Group,type Choice,type Mode,type Matrix,type Trip} from "@/lib/travel/model";
import FranceMap from "./travel-map";
const nameOf=(id:string)=>places.find(p=>p.id===id)?.name||id;
const modeName=(m:Mode)=>m==="car"?"Voiture":"Train";
function nextWeekend(){const n=new Date();const date=new Date(Date.UTC(n.getFullYear(),n.getMonth(),n.getDate()+((5-n.getDay()+7)%7||7)));const fri=date.toISOString().slice(0,10);date.setUTCDate(date.getUTCDate()+2);return [fri,date.toISOString().slice(0,10)];}
const initialDates=nextWeekend();
function ChoicePicker({value,onChange,label,disabled=false}:{value:string;onChange:(v:string)=>void;label:string;disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="both">Voiture ou train</SelectItem><SelectItem value="car">Voiture</SelectItem><SelectItem value="train">Train</SelectItem></SelectContent></Select>}
export default function Home(){
 const [groups,setGroups]=useState<Group[]>(initialGroups);
 const [destinations,setDestinations]=useState(defaultDestinations);
 const [outDate,setOutDate]=useState(initialDates[0]);const [backDate,setBackDate]=useState(initialDates[1]);
 const [outTime,setOutTime]=useState("14:00");const [backTime,setBackTime]=useState("16:00");
 const [matrix,setMatrix]=useState<Matrix>({});const [manual,setManual]=useState<Matrix>({});
 const [tab,setTab]=useState("car");const [scenarioIndex,setScenarioIndex]=useState(0);
 const [selected,setSelected]=useState("bourges");const [busy,setBusy]=useState(false);const [progress,setProgress]=useState({done:0,total:0});
 const [status,setStatus]=useState("Prêt à calculer les trajets.");const [rail,setRail]=useState<RailIndex|null>(null);const [loaded,setLoaded]=useState(false);
 const [manualSource,setManualSource]=useState("SNCF Connect");
 const abort=useRef<AbortController|null>(null);
 const outbound=`${outDate}T${outTime}`,inbound=`${backDate}T${backTime}`;
 const combinations=useMemo(()=>scenarios(groups),[groups]);
 const index=tab==="car"?0:tab==="train"?combinations.length-1:Math.min(scenarioIndex,combinations.length-1);
 const modes=combinations[index];
 const effective=useMemo(()=>({...matrix,...manual}),[matrix,manual]);
 const rows=useMemo(()=>rank(groups,destinations,modes,effective),[groups,destinations,modes,effective]);
 const activeId=destinations.includes(selected)?selected:destinations[0];
 const active=rows.find(r=>r.id===activeId)||rows[0];
 const complete=rows.filter(r=>r.complete);const best=complete[0];
 const comparison=useMemo(()=>combinations.map((m,i)=>({i,m,result:rank(groups,destinations,m,effective).find(r=>r.complete)})).sort((a,b)=>(a.result?.max??Infinity)-(b.result?.max??Infinity)||(a.result?.mean??Infinity)-(b.result?.mean??Infinity)||a.i-b.i),[groups,destinations,combinations,effective]);
 const validDates=!!outDate&&!!backDate&&!!outTime&&!!backTime&&inbound>outbound;
 const railCovers=!!rail&&rail.dates.includes(outDate)&&rail.dates.includes(backDate);
 const frDate=(d:string)=>d.split("-").reverse().join("/");
 function resetForNewDates(){setMatrix({});setManual({});setProgress({done:0,total:0});setStatus("Dates modifiées : relancez le calcul pour ce week-end.");}
 function updateOutDate(v:string){setOutDate(v);resetForNewDates();}
 function updateBackDate(v:string){setBackDate(v);resetForNewDates();}
 function updateOutTime(v:string){setOutTime(v);resetForNewDates();}
 function updateBackTime(v:string){setBackTime(v);resetForNewDates();}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- hydrate persisted preferences after mount (localStorage is unavailable during SSR)
 useEffect(()=>{loadRailIndex().then(setRail);try{const saved=JSON.parse(localStorage.getItem("retrouve.preferences.v1")||"null");if(saved){if(Array.isArray(saved.destinations)&&saved.destinations.length&&saved.destinations.every((id:unknown)=>typeof id==="string"&&places.some(p=>p.id===id)))setDestinations(saved.destinations);if(Array.isArray(saved.groups)&&saved.groups.length>=2&&saved.groups.length<=10&&new Set(saved.groups.map((g:Group)=>g.id)).size===saved.groups.length&&saved.groups.every((g:Group)=>typeof g.id==="string"&&typeof g.name==="string"&&places.some(p=>p.id===g.place)&&(!g.railPlace||places.some(p=>p.id===g.railPlace))&&["both","train","car"].includes(g.choice)&&validMinutes(g.access))){setGroups(saved.groups.map((g:Group)=>g.id==="joel"?{...g,choice:"train"}:g));}}}catch{/* préférences illisibles : on garde les valeurs par défaut */}setLoaded(true);return ()=>abort.current?.abort();},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem("retrouve.preferences.v1",JSON.stringify({groups,destinations}));}catch{/* stockage indisponible */}},[groups,destinations,loaded]);
 function updateGroup(id:string,update:Partial<Group>){setGroups(gs=>gs.map(g=>g.id===id?{...g,...update}:g));setScenarioIndex(0);}
 async function calculate(){if(busy||!validDates||!destinations.length)return;const controller=new AbortController();abort.current=controller;setBusy(true);
 const jobs=new Map<string,{origin:string;destination:string;mode:Mode}>();for(const destination of destinations)for(const g of groups)for(const mode of (g.choice==="both"?["car","train"]:[g.choice]) as Mode[]){const origin=originFor(g,mode);const key=tripKey(origin,destination,mode);if(!matrix[key]?.out||!matrix[key]?.back)jobs.set(key,{origin,destination,mode});}
 setProgress({done:0,total:jobs.size});let done=0,failures=0;
 try{for(const [key,job] of jobs){if(controller.signal.aborted)break;setStatus(`${modeName(job.mode)} · ${nameOf(job.origin)} → ${nameOf(job.destination)}`);
 let result:Trip;
 try{result=await computeTrip(job,outbound,inbound,controller.signal);}catch{if(controller.signal.aborted)break;result={error:"Calcul impossible pour ce trajet. Vous pouvez réessayer."};}
 if(!result.out||!result.back)failures++;setMatrix(prev=>({...prev,[key]:result}));setProgress({done:++done,total:jobs.size});}
 setStatus(controller.signal.aborted?"Calcul arrêté. Les trajets obtenus restent disponibles.":jobs.size===0?"Les trajets de ce week-end sont déjà calculés.":`Calcul terminé. ${failures?`${failures} trajets aller-retour restent à compléter.`:"Tous les trajets sont disponibles."}`);
 }finally{setBusy(false);abort.current=null;}}
 function setManualLeg(g:Group,direction:"out"|"back",value:string){if(!active)return;const key=tripKey(originFor(g,"train"),active.id,"train");setManual(prev=>{const t={...(prev[key]||matrix[key]||{})};delete t.error;if(value===""){delete t[direction];}else{const n=Number(value);if(!validMinutes(n))return prev;t[direction]={minutes:n,source:`Saisie manuelle · ${manualSource.trim()||"source non précisée"}`,retrievedAt:new Date().toISOString()};}return {...prev,[key]:t};});}
 function setDay(kind:"friday"|"saturday"){const base=new Date(`${backDate}T12:00:00Z`);if(!Number.isFinite(base.getTime()))return;const days=kind==="friday"?2:1;base.setUTCDate(base.getUTCDate()-days);setOutDate(base.toISOString().slice(0,10));setOutTime(kind==="friday"?"14:00":"08:00");resetForNewDates();}
 // Browser agents use the same scenario state as the controls.
 useEffect(()=>{type MC={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as Document&{modelContext?:MC}).modelContext;if(!context)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"select_travel_scenario",description:"Sélectionner un scénario existant et afficher ses destinations et durées.",inputSchema:{type:"object",properties:{index:{type:"integer",minimum:0,maximum:combinations.length-1}},required:["index"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const i=(input as {index?:unknown})?.index;if(typeof i!=="number"||!Number.isInteger(i)||i<0||i>=combinations.length)throw Error("Scénario inconnu");setScenarioIndex(i);setTab("scenarios");return {index:i,modes:combinations[i]};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort();},[combinations]);
 return <main><header className="top"><a className="brand" href="./"><span className="brandmark"><MapPin size={22}/></span>On se retrouve<span className="brand-sub">LE WEEK-END, ENSEMBLE</span></a><span className="topnote"><Users size={16}/> {groups.length} groupes de départ</span></header>
 <div className="workspace"><aside className="sidebar"><span className="eyebrow">VOS POINTS DE DÉPART</span><h1>Tout le monde<br/>sur la même carte.</h1><p className="muted">Les modes flexibles créent les scénarios.</p><div className="groups">{groups.map((g,i)=><section className="group" key={g.id}><div className="group-heading"><span className="number">0{i+1}</span><strong>{g.name}</strong></div><p>{nameOf(g.place)}</p><small>{g.note}</small><div className="group-controls"><ChoicePicker value={g.choice} label={`Transport de ${g.name}`} onChange={v=>updateGroup(g.id,{choice:v as Choice})} disabled={busy||g.id==="joel"}/></div><details className="group-details"><summary>Modifier le départ</summary><fieldset disabled={busy}><label>Nom<input aria-label={`Nom du groupe ${i+1}`} value={g.name} maxLength={70} onChange={e=>updateGroup(g.id,{name:e.target.value})}/></label><label>Ville<Select value={g.place} onValueChange={v=>updateGroup(g.id,{place:v,railPlace:undefined})}><SelectTrigger aria-label={`Ville de ${g.name}`}><SelectValue/></SelectTrigger><SelectContent>{places.map(p=><SelectItem value={p.id} key={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></label><label>Départ en train<Select value={g.railPlace||g.place} onValueChange={v=>updateGroup(g.id,{railPlace:v})}><SelectTrigger aria-label={`Départ ferroviaire de ${g.name}`}><SelectValue/></SelectTrigger><SelectContent>{places.map(p=><SelectItem value={p.id} key={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></label><label>Accès / marge train, par sens (min)<input type="number" min="0" max="240" value={g.access} onChange={e=>updateGroup(g.id,{access:Math.max(0,Math.min(240,Number(e.target.value)||0))})}/></label>{groups.length>2&&<button className="text-button danger" onClick={()=>setGroups(gs=>gs.filter(x=>x.id!==g.id))}>Retirer ce groupe</button>}</fieldset></details></section>)}</div>{groups.length<10&&<button className="text-button add" disabled={busy} onClick={()=>setGroups(gs=>[...gs,{id:crypto.randomUUID(),name:"Nouveau groupe",place:"paris",choice:"both",note:"Départ à personnaliser",access:0}])}><Plus size={16}/> Ajouter un groupe</button>}<div className="sidebar-foot"><Info size={16}/><p>Un même poids pour chaque groupe. Clermont voyage dans une seule voiture.</p></div></aside>
 <section className="mainpane"><div className="heading"><div><span className="eyebrow">LE BON ENDROIT POUR TOUS</span><h2>Où se retrouver ?</h2></div><span className="pill">{combinations.length} scénarios possibles</span></div>
 <section className="card dates-card"><div className="section-label"><CalendarDays size={18}/><strong>Votre week-end</strong><div className="quick-days"><button disabled={busy} onClick={()=>setDay("friday")}>Dès vendredi</button><button disabled={busy} onClick={()=>setDay("saturday")}>Dès samedi</button></div></div><fieldset className="date-fields" disabled={busy}><label>Départ à partir de<span className="date-pair"><input type="date" aria-label="Date de départ" value={outDate} onChange={e=>updateOutDate(e.target.value)}/><input type="time" aria-label="Heure de départ" value={outTime} onChange={e=>updateOutTime(e.target.value)}/></span></label><ArrowRight size={20} className="date-arrow"/><label>Retour à partir de<span className="date-pair"><input type="date" aria-label="Date de retour" value={backDate} onChange={e=>updateBackDate(e.target.value)}/><input type="time" aria-label="Heure de retour" value={backTime} onChange={e=>updateBackTime(e.target.value)}/></span></label><button className="primary calculate" disabled={!validDates||!destinations.length} onClick={calculate}>{busy?<LoaderCircle size={18} className="spin"/>:<ArrowRight size={18}/>} {busy?"Calcul en cours…":"Calculer les trajets"}</button></fieldset>{!validDates&&<p className="error" role="alert">Choisissez un retour après le départ.</p>}<div className="calculation-status" role="status"><span>{status}</span>{busy&&<button onClick={()=>abort.current?.abort()} className="text-button">Arrêter</button>}</div>{busy&&<Progress aria-label="Trajets calculés" value={progress.total?progress.done/progress.total*100:0}/>}</section>
 <div className="rail-notice"><TrainFront size={18}/><p>{rail?(railCovers?<>Horaires SNCF théoriques (GTFS du {frDate(rail.feedVersion)}) précalculés pour ces dates : trains recherchés dans les six heures suivant l’heure choisie, trois correspondances au plus. Les temps routiers viennent de l’IGN.</>:<>Les horaires de train sont précalculés pour les vendredis, samedis et dimanches du {frDate(rail.dates[0]??"")} au {frDate(rail.dates[rail.dates.length-1]??"")}. Pour d’autres dates, <a href="#manual">complétez les durées de train</a>.</>):<>Horaires de train indisponibles. <a href="#manual">Complétez les durées de train</a> pour obtenir un classement. Les temps routiers se calculent automatiquement.</>}</p></div>
 <Tabs value={tab} onValueChange={setTab} className="scenario-tabs"><TabsList aria-label="Scénario de transport" className="scenario-list"><TabsTrigger value="car"><Car size={16}/> Voiture si possible</TabsTrigger><TabsTrigger value="train"><TrainFront size={16}/> Train si possible</TabsTrigger><TabsTrigger value="scenarios"><Settings2 size={16}/> Tous les scénarios</TabsTrigger></TabsList><TabsContent value="car"><p className="scenario-help">Les groupes flexibles conduisent ; les groupes en train le restent.</p></TabsContent><TabsContent value="train"><p className="scenario-help">Tous les groupes flexibles prennent le train.</p></TabsContent><TabsContent value="scenarios"><div className="scenario-select"><Select value={String(index)} onValueChange={v=>setScenarioIndex(Number(v))}><SelectTrigger aria-label="Choisir un scénario"><SelectValue/></SelectTrigger><SelectContent>{combinations.map((m,i)=><SelectItem key={i} value={String(i)}>Scénario {i+1} · {m.filter(x=>x==="car").length} voiture / {m.filter(x=>x==="train").length} train</SelectItem>)}</SelectContent></Select><span className="muted">Le détail des modes apparaît sous la carte.</span></div></TabsContent></Tabs>
 <div className="result-grid"><section className="card map-card"><div className="map-heading"><span className="eyebrow">FRANCE · {destinations.length} VILLES COMPARÉES</span><span className="map-legend"><i/> Départs <i className="dest-dot"/> Destinations</span></div><FranceMap groups={groups} destinations={destinations} selected={active?.id} onSelect={setSelected} ranked={complete.map(r=>r.id)}/><div className="map-caption">Sélectionnez une destination sur la carte. Les traits relient les villes et ne représentent pas les itinéraires.</div></section>
 <section className="card ranking-card"><div className="ranking-heading"><span className="eyebrow">ÉQUITÉ DES TRAJETS</span><h3>{best?"Les meilleurs compromis":"Destinations à comparer"}</h3><p className="muted">Plus long trajet, puis temps moyen.</p></div>{best&&<div className="best-metric"><span>Trajet le plus long à {nameOf(best.id)}</span><strong>{duration(best.max)}</strong></div>}<div className="destination-list">{rows.map((r,i)=><button key={r.id} onClick={()=>setSelected(r.id)} className={`destination-row ${active?.id===r.id?"selected":""}`}><span className="rank-number">{r.complete?String(i+1).padStart(2,"0"):"·"}</span><span className="destination-title">{nameOf(r.id)}<small>{r.complete?`Moyenne ${duration(r.mean)} / sens`:`${r.known}/${groups.length*2} durées disponibles`}</small></span><span className="destination-time">{r.complete?duration(r.max):"À compléter"}</span></button>)}</div><div className="ranking-footer">{complete.length}/{destinations.length} destinations classables · aucune durée manquante n’est remplacée par zéro.</div></section></div>
 {active&&<section className="card detail-card"><div className="detail-heading"><div><span className="eyebrow">SCÉNARIO {index+1} · DURÉES PAR GROUPE</span><h3>On se retrouve à {nameOf(active.id)}</h3></div><span className="pill neutral">{active.complete?`Maximum ${duration(active.max)}`:"Comparaison incomplète"}</span></div><Table><TableHeader><TableRow><TableHead>Qui part ?</TableHead><TableHead>Transport</TableHead><TableHead>Aller</TableHead><TableHead>Retour</TableHead><TableHead>Source / horaires</TableHead></TableRow></TableHeader><TableBody>{active.trips.map((t,i)=><TableRow key={t.group}><TableCell><strong>{groups[i].name}</strong><small className="block muted">{nameOf(originFor(groups[i],t.mode))}</small></TableCell><TableCell><span className={`mode-badge ${t.mode}`}>{t.mode==="car"?<Car size={15}/>:<TrainFront size={15}/>} {modeName(t.mode)}</span></TableCell><TableCell className="time-cell">{duration(t.out)}</TableCell><TableCell className="time-cell">{duration(t.back)}</TableCell><TableCell className="source-cell">{t.trip?.out?.source||t.trip?.error||"À calculer"}{t.trip?.out?.departure&&<small className="block">Aller : {displayRailTime(t.trip.out.departure)} → {displayRailTime(t.trip.out.arrival)} · {t.trip.out.transfers??0} correspondance(s){t.trip.out.via&&<> · {t.trip.out.via.join(" › ")}</>}</small>}{t.trip?.back?.departure&&<small className="block">Retour : {displayRailTime(t.trip.back.departure)} → {displayRailTime(t.trip.back.arrival)}</small>}{t.mode==="train"&&groups[i].access>0&&<small className="block">+ {groups[i].access} min d’accès / marge par sens</small>}<a className="route-link" target="_blank" rel="noreferrer" href={directions(nameOf(originFor(groups[i],t.mode)),nameOf(active.id),t.mode)}>Vérifier le trajet <ExternalLink size={12}/></a></TableCell></TableRow>)}</TableBody></Table><p className="detail-note">Voiture : centres-villes, hors trafic et pauses. Train : selon l’itinéraire fourni ; ajoutez votre accès à la gare dans les paramètres du groupe. Même ville : trajet local non inclus.</p></section>}
 {active&&<details className="card manual-card" id="manual" open={!railCovers}><summary><TrainFront size={18}/><strong>Compléter les trains pour {nameOf(active.id)}</strong><ChevronDown size={18}/></summary><div className="manual-body"><p className="muted">Saisissez les durées vérifiées pour ce week-end, correspondances comprises, en minutes. Elles s’appliquent aux groupes ayant le même départ ferroviaire. Changer les dates efface ces saisies.</p><label className="source-input">Source consultée<input value={manualSource} maxLength={120} onChange={e=>setManualSource(e.target.value)} placeholder="SNCF Connect, horaire consulté…"/></label><div className="manual-grid">{groups.filter((g,i)=>g.choice!=="car"&&groups.findIndex(h=>originFor(h,"train")===originFor(g,"train"))===i).map(g=>{const key=tripKey(originFor(g,"train"),active.id,"train");const t=manual[key];return <div className="manual-row" key={g.id}><div><strong>{nameOf(originFor(g,"train"))}</strong><a className="route-link" target="_blank" rel="noreferrer" href={directions(nameOf(originFor(g,"train")),nameOf(active.id),"train")}>Consulter le trajet <ExternalLink size={12}/></a></div><label>Aller (min)<input type="number" min="0" max="2880" step="1" aria-label={`Train aller depuis ${nameOf(originFor(g,"train"))}`} value={t?.out?.minutes??""} placeholder="—" disabled={busy} onChange={e=>setManualLeg(g,"out",e.target.value)}/></label><label>Retour (min)<input type="number" min="0" max="2880" step="1" aria-label={`Train retour vers ${nameOf(originFor(g,"train"))}`} value={t?.back?.minutes??""} placeholder="—" disabled={busy} onChange={e=>setManualLeg(g,"back",e.target.value)}/></label></div>})}</div></div></details>}
 <details className="card settings-card"><summary><MapPin size={18}/><strong>Les villes comparées</strong><ChevronDown size={18}/></summary><div className="settings-body"><p className="muted">La meilleure destination est recherchée parmi cette sélection, pas parmi toutes les communes de France.</p><div className="city-checks">{places.map(p=><label key={p.id}><Checkbox checked={destinations.includes(p.id)} disabled={busy||(destinations.length===1&&destinations[0]===p.id)} onCheckedChange={checked=>setDestinations(prev=>checked?[...prev,p.id]:prev.filter(id=>id!==p.id))}/>{p.name}</label>)}</div></div></details>
 <details className="card settings-card"><summary><Settings2 size={18}/><strong>Comparer les {combinations.length} scénarios</strong><ChevronDown size={18}/></summary><Table><TableHeader><TableRow><TableHead>Scénario</TableHead><TableHead>Meilleure ville</TableHead><TableHead>Maximum</TableHead><TableHead>Moyenne / sens</TableHead><TableHead/></TableRow></TableHeader><TableBody>{comparison.map(c=><TableRow key={c.i}><TableCell>{c.i+1} · {c.m.map(m=>m==="car"?"V":"T").join(" / ")}</TableCell><TableCell>{c.result?nameOf(c.result.id):"Données incomplètes"}</TableCell><TableCell>{duration(c.result?.max)}</TableCell><TableCell>{duration(c.result?.mean)}</TableCell><TableCell><button className="text-button" onClick={()=>{setTab("scenarios");setScenarioIndex(c.i);if(c.result)setSelected(c.result.id);}}>Afficher</button></TableCell></TableRow>)}</TableBody></Table><p className="detail-note">V = voiture, T = train. Ordre des groupes identique à la liste des départs.</p></details>
 <footer className="method"><Info size={18}/><div><strong>Comment le classement fonctionne</strong><p>On minimise la plus longue durée parmi tous les allers et retours. À égalité, on minimise la moyenne, avec le même poids par groupe. Les dates sont en heure française. La durée ne comprend pas l’attente avant le départ choisi. Pour le train, on retient le trajet le plus court parmi les départs des six heures suivant l’heure choisie, avec dix minutes minimum par correspondance ; les horaires sont théoriques et rafraîchis chaque semaine. Les préférences sont conservées sur cet appareil ; les durées saisies restent dans cette session.</p><p>Sources : <a href="https://www.data.gouv.fr/dataservices/api-geoplateforme-calcul-ditineraire" target="_blank" rel="noreferrer">IGN Géoplateforme</a> · <a href="https://transport.data.gouv.fr/datasets/horaires-sncf" target="_blank" rel="noreferrer">Horaires SNCF (GTFS, transport.data.gouv.fr)</a> · <a href="https://github.com/gregoiredavid/france-geojson" target="_blank" rel="noreferrer">Contours France GeoJSON</a></p></div></footer>
 </section></div></main>
}
function directions(origin:string,destination:string,mode:Mode){const p=new URLSearchParams({api:"1",origin:origin+", France",destination:destination+", France",travelmode:mode==="car"?"driving":"transit"});return `https://www.google.com/maps/dir/?${p}`;}
function displayRailTime(value?:string){if(!value)return "—";if(/^\d{4}-\d{2}-\d{2}T/.test(value))return value.slice(11);return /^\d{8}T\d{6}$/.test(value)?`${value.slice(6,8)}/${value.slice(4,6)} ${value.slice(9,11)}:${value.slice(11,13)}`:value;}
